---
- name: Instalar docker
  become: yes
  hosts: tag_type_docker
  roles:
    - docker

- name: Subir container MySQL
  become: yes
  hosts:  tag_Name_telemetria0
  roles:
    - telemetria0

- name: gather ec2 facts per instance
  hosts: tag_Name_telemetria0
  gather_facts: True
  tasks:
    - ec2_metadata_facts:
    - name: debug
      debug: var=ansible_ec2_local_ipv4
      register: ipprivado 
    - local_action: copy content="{{ ipprivado }}" dest="roles/telemetria1/vars/main.yml"  

- name: Subir container WordPress
  become: yes
  hosts:  tag_Name_telemetria1
  roles:
    - telemetria1
