- name: launch Word-Press container
  docker_container:
    name: meublog
    image: wordpress:latest
    state: started
    env:
      WORDPRESS_DB_HOST: "{{ ansible_ec2_local_ipv4 }}"
      WORDPRESS_DB_PASSWORD: "123456"
      WORDPRESS_DB_NAME: "mydb"
      WORDPRESS_TABLE_PREFIX: "wp"
    ports:
     - "8080:80"